name: Check Factorio Updates

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:     # Возможность ручного запуска

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # или '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python bot.py

    - name: Commit updated files (если обновились)
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add last_hash.txt last_pin.txt || true
        git diff --cached --quiet || (git commit -m "Update state files" && git push)
